/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_Tensosense                     11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_model_number_string            18
#define gattdb_hardware_revision_string       20
#define gattdb_firmware_revision_string       22
#define gattdb_system_id                      24
#define gattdb_led_control                    27
#define gattdb_report_button                  29
#define gattdb_analog_0                       32
#define gattdb_characteristic_presentation_format 34
#define gattdb_characteristic_user_description 35
#define gattdb_characteristic_extended_properties 36
#define gattdb_value_trigger_setting          37
#define gattdb_time_trigger_setting           38
#define gattdb_valid_range                    39
#define gattdb_imu_acceleration               42
#define gattdb_imu_orientation                45
#define gattdb_imu_control_point              48
#define gattdb_tx_power_0                     50
#define gattdb_tx_power_level                 52
#define gattdb_ota                            53
#define gattdb_ota_control                    55


#endif // __GATT_DB_H
